name: dark_router
description: A extension package for go_router to support query parameters generation and making life easy for you with other usefull features.
version: 0.1.2

repository: https://github.com/Dark-in-Star/dark_router
homepage:  https://github.com/Dark-in-Star/dark_router
issue_tracker: https://github.com/Dark-in-Star/dark_router/issues

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  build: ^2.4.0
  source_gen: ^1.5.0
  analyzer: ^6.2.0
  go_router: ^16.1.0

dev_dependencies:
  build_runner: ^2.4.0