name: dark_router
description: A extension package for go_router to support query parameters generation and making life easy for you with other usefull features.
version: 0.0.1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  build: ^2.4.0
  source_gen: ^1.5.0
  analyzer: ^6.2.0

dev_dependencies:
  build_runner: ^2.4.0